version: '3.5'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: pjcapp
    ports:
      - 5432:5432
    volumes:
      - my_db:/var/lib/postgresql/data
  minio:
    image: minio/minio:latest
    restart: always
    environment:
      MINIO_ROOT_USER: AmongUs
      MINIO_ROOT_PASSWORD: AmongUsRootPassword
    ports:
      - 9000:9000
    volumes:
      - my_min_io:/data
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
volumes:
  my_db:
  my_min_io:
